#ifndef MAIN_INC_H
#define MAIN_INC_H

/* This file is autogenerated, do not edit manually! */
#include "fir_float.h"
#include "iir_float.h"

/* Define the frequency at which the waveform is sampled */
#define SAMPLING_FREQUENCY 16000

/* Make the necessary symbols visible publically */
extern struct sos_filter_float_t sos_filt;
extern struct iir_float_t iir_filt;
extern struct fir_float_t fir_filt;

extern struct fir_float_t fir_decimation_filt;

#endif /* MAIN_INC_H */
