#ifndef SPECTRUM_GEN_SHARED_H
#define SPECTRUM_GEN_SHARED_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	AMPLITUDE_SPECTRUM_FLAT,
	AMPLITUDE_SPECTRUM_LOW_DECAY,
	AMPLITUDE_SPECTRUM_HIGH_DECAY,
	AMPLITUDE_SPECTRUM_BANDPASS,
	AMPLITUDE_SPECTRUM_BANDSTOP,
	AMPLITUDE_SPECTRUM_LOW_BOOST,
	AMPLITUDE_SPECTRUM_HIGH_BOOST
} AMPLITUDE_SPECTRUM_E;

#ifdef __cplusplus
}
#endif

#endif /* SPECTRUM_GEN_SHARED_H */
